config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'lists#index'
  resources :lists, only:[:new, :create, :index, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmark, only: [:destroy]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(strong_params)
    @bookmark.list = @list
    if @bookmark.save
      # when it saves -> go to the restaurants show page
      redirect_to list_path(@list)
    else
      # when it doesnt save -> show the form again
      render 'list/show', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

   private

  def strong_params
    # Strong params -> white listing the attributes users can give us in the form
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

# 4 - Routing, Controller, Views for bookmarks

#     A user can add a new bookmark (movie/list pair) to an existing list
#     Check out simple_form docs about f.association to easily create a select dropdown for our list of movies.

# GET "lists/42/bookmarks/new"
# POST "lists/42/bookmarks"

#     A user can delete a bookmark from a list. How can we make a delete link again?

# DELETE "bookmarks/25"

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      # when it saves -> go to the restaurants show page
      redirect_to list_path(@list)
    else
      # when it doesnt save -> show the form again
      render 'new', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  private

  def list_params
    # Strong params -> white listing the attributes users can give us in the form
    params.require(:list).permit(:name, :photo)
  end
end



# Features

# Once again, you must have a precise idea of the features of your app in order to build your routes. Here is the list of features:

#     A user can see all the lists

# GET "lists"

#     A user can see the details of a given list and its name

# GET "lists/42"

#     A user can create a new list

# GET "lists/new"
# POST "lists"

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class='container'>
  <h1> Lists </h1>
  <ul class="index-list">
    <% @lists.each do |list| %>
      <li style="list-style-type: none">
        <div class="item card-category m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU') %>)">
          <%= link_to list.name, list_path(list), class: 'text-decoration-none text-primary' %>
        </div>
      </li>
    <% end %>
    <ul>
      <%= link_to "New", new_list_path, class: 'btn btn-primary mx-3' %>
    </div>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: 'btn btn-primary mt-3' %>
<% end %>

app/views/lists/show.html.erb
<div class="item card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : image_path('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU') %>)">
  <%= @list.name %>
</div>
<!-- BACKGROUND IMAGE -->
<div class="container  ">
  <%# show bookmarks (movies) %>
  <div class="container m-3">
    <h2>Movies</h2>
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= bookmark.movie.poster_url %>')">
        <%= bookmark.movie.title %>
      </div>
      <p><strong>Overview: </strong><%=bookmark.movie.overview %></p>
      <p><strong>Rating: </strong><%=bookmark.movie.rating %></p>
      <p><strong>comment: </strong><%=bookmark.comment %></p>
    <% end %>
    <%= link_to "Home", lists_path, class: 'btn btn-primary' %>
  </div>
  <%# form to make bookmarks %>
  <div class="container m-3">
    <h2>Make bookmarks</h2>
    <p>Bookmark movies for this list!</p>
    <%= simple_form_for [ @list, @bookmark ] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie, collection: @movies, prompt: 'Select Movie', label: false %>
      <%= f.submit "Submit", class: 'btn btn-primary mt-3' %>
    <% end %>
  </div>
  <%# simpole form only needs f.association :movie, not all that other stuff i have. %>
</div>